## Задание 1
>*Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно*

In [1]:
import numpy as np

In [ ]:
a = np.arange(12, 24)
print(f'a = {a}')

a = [12 13 14 15 16 17 18 19 20 21 22 23]


## Задание 2
>*Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.*

In [ ]:
# функция reshape преобразует массив из одной формы в другую
a1 = a.reshape(2, 6)
print('a1 :')
print(a1)
a2 = a.reshape(3, 4)
print('a2 :')
print(a2)
a3 = a.reshape(4, 3)
print('a3 :')
print(a3)
a4 = a.reshape(6, 2)
print('a4 :')
print(a4)
a5 = a.reshape(12, 1)
print('a5 :')
print(a5)

a1 :
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a2 :
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a3 :
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a4 :
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a5 :
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


## Задание 3
>*Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).*

In [ ]:
# -1 используется чтобы Numpy.reshape сам определил необходимое количество строк или столбцов
a6 = a.reshape(2, -1)
print('a6 :')
print(a6)
a7 = a.reshape(3, -1)
print('a7 :')
print(a7)
a8 = a.reshape(4, -1)
print('a8 :')
print(a8)

a9 = a.reshape(-1, 2)
print('a9 :')
print(a9)
a10 = a.reshape(-1, 1)
print('a10 :')
print(a10)

a6 :
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a7 :
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a8 :
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a9 :
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a10 :
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


## Задание 4
>*Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?*

In [ ]:
# Ответ - нет, нельзя. Указанные массив имеет размерность - 2
# Массив a10 состоит из одного столбца и 12 строк.
print(a10)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [ ]:
print(f'Размерность массива а10 = {a10.ndim}')

Размерность массива а10 = 2


## Задание 5
>*Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.*

In [ ]:
# функция randn возвращает массив ndarray с числами с плавающей запятой в нормальном распределении (Гаусс)
b = np.random.randn(3, 4)
print('Массив b:')
print(b)
print(f'Size b = {b.size}, форма b = {b.shape}, размерность b = {b.ndim}')

Массив b:
[[-0.07443934 -1.39094309 -0.78861789  0.43677708]
 [-0.50281362  0.4201058   0.98864058  0.46110293]
 [ 1.55606767 -0.04485689  2.21963714  1.42213953]]
Size b = 12, форма b = (3, 4), размерность b = 2


In [ ]:
# для получения одномерного массива из многомерного, используется метод (функция) flatten
b1 = b.flatten()
print('Массив b1:')
print(b1)
print(f'Size b1 = {b1.size}, форма b1 = {b1.shape}, размерность b1 = {b1.ndim}')
print()
# использование метода reshape не позволяет получить одномерные массив - можно сравнить результаты
b2 = b.reshape(1, -1)
print('Массив b2:')
print(b2)
print(f'Size b2 = {b2.size}, форма b2 = {b2.shape}, размерность b2 = {b2.ndim}')

Массив b1:
[-0.07443934 -1.39094309 -0.78861789  0.43677708 -0.50281362  0.4201058
  0.98864058  0.46110293  1.55606767 -0.04485689  2.21963714  1.42213953]
Size b1 = 12, форма b1 = (12,), размерность b1 = 1

Массив b2:
[[-0.07443934 -1.39094309 -0.78861789  0.43677708 -0.50281362  0.4201058
   0.98864058  0.46110293  1.55606767 -0.04485689  2.21963714  1.42213953]]
Size b2 = 12, форма b2 = (1, 12), размерность b2 = 2


## Задание 6
>*Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.*

In [ ]:
# отрицательное значение последнего параметра предполагает создание убывающей последовательности
a = np.arange(20, 0, -2)
print(a)
print(f'Size a = {a.size}, форма a = {a.shape}, размерность a = {a.ndim}')

[20 18 16 14 12 10  8  6  4  2]
Size a = 10, форма a = (10,), размерность a = 1


## Задание 7
>*Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?*

In [ ]:
# отрицательное значение последнего параметра предполагает создание убывающей последовательности
b = np.arange(20, 1, -2).reshape(1, 10)
print(b)
print(f'Size b = {b.size}, форма b = {b.shape}, размерность b = {b.ndim}')
print('Разница в том, что - массив a - одномерный массив (вектор), с размерностью 1. Массив b - матрица, имеет размерность 2')

# массив a - одномерный массив (вектор), с размерностью 1. Массив b - матрица, имеет размерность 2

[[20 18 16 14 12 10  8  6  4  2]]
Size b = 10, форма b = (1, 10), размерность b = 2
Разница в том, что - массив a - одномерный массив (вектор), с размерностью 1. Массив b - матрица, имеет размерность 2


## Задание 8
>*Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.*

In [ ]:
# создание массива состоящего из нулей
a = np.zeros((2, 2))
# создание массива, состоящего из единиц    
b = np.ones((3, 2))
# вертикальное объединение массивов
v = np.vstack((a,b))
print('Массив а:')
print(a)
print('Массив b:')
print(b)
print('Массив v:')
print(v)
print(f'Размер массива v = {v.size}')


Массив а:
[[0. 0.]
 [0. 0.]]
Массив b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Массив v:
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Размер массива v = 10


## Задание 9
>*Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?*

In [2]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = np.dot(A, At)
print(B)
print(f'Размер матрицы B = {B.size}, форма = {B.shape}, размерность = {B.ndim}')
# Обратная матрица - это матрица, при умножению на которую получаем единичную матрицу
print('Обратная матрица - это матрица, при умножению на которую получаем единичную матрицу')
# Алгоритм нахождения обратной матрицы
# 1. Определяем является ли наша матрица квадратной? Если не квадратная, то обратной матрицы не существует
print(f'Форма матрицы B = {B.shape}')
print('Матрица B - квадратная. Переходим к следующему шагу')
# 2. Считаем определитель матрицы. Если определитель = 0, то обратной матрицы не существует
print(f'Определитель матрицы B = {np.linalg.det(B)}')
print('Определитель матрицы B = 0. Стоп! - обратной матрицы, для матриы B - не существует!')

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Размер матрицы B = 16, форма = (4, 4), размерность = 2
Обратная матрица - это матрица, при умножению на которую получаем единичную матрицу
Форма матрицы B = (4, 4)
Матрица B - квадратная. Переходим к следующему шагу
Определитель матрицы B = 0.0
Определитель матрицы B = 0. Стоп! - обратной матрицы, для матриы B - не существует!


## Задание 10
>*Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.*

In [ ]:
# если вызывать seed перед каждым вызовом "случайных функций", то результат будет одинаковый
np.random.seed(42)
a = np.random.rand(3)
print(a)
np.random.seed(42)
b = np.random.rand(3)
print(b)

[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]


In [ ]:
# если вызвать seed один раз, а потом вызывать "случайные функции", то результат все равно будет разный
np.random.seed(42)
a = np.random.rand(3)
print(a)
b = np.random.rand(3)
print(b)

[0.37454012 0.95071431 0.73199394]
[0.59865848 0.15601864 0.15599452]


## Задание 11
>*Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.*

In [4]:
# функции randint, random_integer, random_sample, rand - дают равномерное распределение
c = np.random.randint(0, 16, size=16)
c


array([ 0,  2,  7,  5,  1,  0,  5, 15,  3,  9,  6,  5, 14, 10,  0,  6])

## Задание 12
>*Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.*

In [5]:
C = c.reshape(4, -1)
# умножение матрицы на скаляр (С*10) и сложение матриц поэлементно
D = B + C*10
print(f'Определитель матрицы D = {np.linalg.det(D)}')
print(f'Ранг матрицы D = {np.linalg.matrix_rank(D)}')
D_inv = np.linalg.inv(D)
print('Обратная матрица для матрицы D:')
# настроим немного печать матриц - если float это малое число, то будет печататься 0
# если параметр suppress=False (по умолчанию), то такие числа будут печататься в научном формате, с большой минусовой степенью
np.set_printoptions(suppress=True)
print(D_inv)
# проверяем - умножение матрицы на обратную должно дать единичную матрицу
print('Результат умножения матрицы D на обратную матрицу D_inv:')
print(D.dot(D_inv))


Определитель матрицы D = -131108399.99999994
Ранг матрицы D = 4
Обратная матрица для матрицы D:
[[ 0.01693423 -0.00440201 -0.01555339  0.01072853]
 [-0.02074253 -0.0036675   0.01525333 -0.00358543]
 [ 0.02750838 -0.00465188 -0.00622035  0.00176617]
 [-0.01143542  0.00706499  0.00167861 -0.00117063]]
Результат умножения матрицы D на обратную матрицу D_inv:
[[ 1. -0. -0.  0.]
 [-0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


## Задание 13
>*Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.*

In [6]:
# Условие в квадратных скобках является битовой маской, то есть запись D_inv[D_inv < 0] - 
# возвращает элементы матрицы D_inv, удовлетворяющие условию внутри квадратных скобок
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
print(D_inv)

[[1. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]


In [11]:
# Матрица D_inv используется как маска в функции np.where: для позиций элементов, где удовлетворяется
# условие D_inv == 1, в итоговую матрицу берутся элементы из матрицы B, в позициях, где условие
# False в итоговую матрицу вставляются элементы из соответствующей позиции матрицы С
E = np.where(D_inv == 1, B, C)
print('Матрица D_inv:')
print(D_inv)
print('Матрица B:')
print(B)
print('Матрица C:')
print(C)
print('Матрица E:')
print(E)

Матрица D_inv:
[[1. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]
Матрица B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица C:
[[ 0  2  7  5]
 [ 1  0  5 15]
 [ 3  9  6  5]
 [14 10  0  6]]
Матрица E:
[[  5   2   7  32]
 [  1   0  86  15]
 [ 23   9   6 212]
 [ 14 122 212   6]]
